config/routes.rb
Rails.application.routes.draw do
  root "home#index"

  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  get "/signup", to: "users#new"
  post "/signup", to: "users#create"

  resources :users, only: %i{new create}
  resources :categories, only: %i{new create}
  resources :items, only: %i{new create}
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :detail_orders, dependent: :destroy
  has_many :items, through: :detail_orders

  def sub_total
    sum = 0
    detail_orders.each do |line_item|
      sum += line_item.total_price
    end
    sum
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :items, dependent: :destroy

  scope :load_navi, ->{order :name}

  validates :name, presence: true
end

app/models/detail_order.rb
class DetailOrder < ApplicationRecord
  belongs_to :order, optional: true
  belongs_to :item, optional: true
  belongs_to :cart, optional: true

  before_create :set_quantity

  def total_price
    quantity * item.price
  end

  private
  def set_quantity
    self.quantity = 1
  end
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :reviews, dependent: :destroy
  has_many :order_details, dependent: :destroy
  belongs_to :category

  scope :sort_by_name, ->{order :name}
  scope :load_cate, ->(cate){where(category_id: cate)}

  has_one_attached :image
  validates :name, presence: true
  validates :price, presence: true
  validates :quantity, presence: true
  validates :image, content_type: {in: %w(image/jpeg image/gif image/png),
                                   message:
                                    I18n.t("item.image_1")},
   size: {less_than: 5.megabytes, message:
    I18n.t("item.image_2")}

  def display_image
    image.variant resize_to_limit: [Settings.item.image.default,
      Settings.item.image.default]
  end
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :detail_orders, dependent: :destroy
  belongs_to :user, optional: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :item
end

app/models/user.rb
class User < ApplicationRecord
  has_many :reviews, dependent: :destroy
  has_many :orders, dependent: :destroy

  before_save :downcase_email

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i.freeze
  validates :name, presence: true
  validates :email, presence: true,
    length: {maximum: Settings.user.email.size},
    format: {with: VALID_EMAIL_REGEX},
    uniqueness: true
  validates :phone, presence: true
  validates :address, presence: true

  has_secure_password

  def self.digest string
    cost = if ActiveModel::SecurePassword.min_cost
             BCrypt::Engine::MIN_COST
           else
             BCrypt::Engine.cost
           end
    BCrypt::Password.create string, cost: cost
  end

  private

  def downcase_email
    email.downcase!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  include ItemsHelper
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @cart = @current_cart
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:success] = t("category.add_cate_success")
      redirect_to new_category_path
    else
      flash.now[:danger] = t("category.add_cate_fail")
      render :new
    end
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/detail_orders_controller.rb
class DetailOrdersController < ApplicationController
  def index; end

  def show; end

  def new; end

  def create
    chosen_item = Item.find_by(id: params[:item_id])
    current_cart = @current_cart
    build_detail_order chosen_item, current_cart
    if @detail_order.save
      flash[:success] = t("carts.add_cart_success")
    else
      flash[:danger] = t("carts.add_cart_faild")
    end
    redirect_to cart_path(current_cart)
  end

  def destroy
    @detail_order = DetailOrder.find_by(id: params[:id])
    if @detail_order.destroy
      flash[:success] = t("carts.remove_success")
    else
      flash[:danger] = t("carts.remove_faild")
    end
    redirect_to cart_path(@current_cart)
  end

  private

  def detail_order_params
    params.require(:detail_order).permit(:quantity, :item_id, :cart_id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :load_item_by_cate, only: %i(index)

  def index
    @items = Item.paginate(page: params[:page],
      per_page: Settings.item.item_on_page).sort_by_name
    @categories = Category.load_navi
    load_item_by_cate
  end

  private

  def load_item_by_cate
    return if params[:cate].nil?

    @items = Item.paginate(page: params[:page], per_page:
      Settings.item.item_on_page).load_cate(params[:cate]).sort_by_name
    return unless @items.empty?

    flash.now[:danger] = t("item.no_result_with_cate")
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :check_cate, only: %i(new create)

  def new
    @item = Category.item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      flash[:success] = t "item.create_success"
      redirect_to root_path
    else
      flash.now[:danger] = t "item.create_fail"
      render :new
    end
  end

  private

  def item_params
    params.require(:item).permit(:name,
                                 :category_id, :description, :price,
                                 :image, :quantity)
  end

  def check_cate
    return if Category.all.empty?

    flash.now[:success] = t "category.no_cate"
    render :new
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.find_by email: params[:session][:email].downcase
    if user&.authenticate(params[:session][:password])
      login user
      redirect_to root_path
    else
      flash.now[:danger] = t("danger_login")
      redirect_to login_path
    end
  end

  def destroy
    logout
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = t("message_register_success")
      redirect_to root_path
    else
      flash.now[:danger] = t("message_register_error")
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :phone, :address, :password,
                                 :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
  def current_cart
    if session[:cart_id]
      cart = Cart.find_by(id: session[:cart_id])
      if cart.present?
        @current_cart = cart
      else
        session[:cart_id] = nil
      end
    end
    return unless session[:cart_id].nil?

    @current_cart = Cart.create
    session[:cart_id] = @current_cart.id
  end
end

app/helpers/detail_orders_helper.rb
module DetailOrdersHelper
end

app/helpers/items_helper.rb
module ItemsHelper
  def list_category
    Category.pluck(:name)
  end

  def load_item_by_cate
    @categories = Category.all
    cate = params[:cate]
    return if cate.nil?

    @items = Item.load_cate(cate)
    return unless @items.empty?

    flash.now[:danger] = t("item.no_result_with_cate")
  end

  def load_or_search_item
    if params[:search]
      @items = Item.search_item(params[:search])
      return unless @items.empty?

      flash.now[:danger] = t("item.no_result")
    else
      @items = Item.all
    end
  end

  def load_same_item
    samecate = params[:same_cate]
    @item_same_cate = Item.same_cate samecate
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def login user
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by id: session[:user_id]
  end

  def logged_in?
    current_user.present?
  end

  def logout
    session.delete(:user_id)
    @current_user = nil
  end
end

app/views/carts/_line_item.html.erb
<% @cart.detail_orders.each do |line_item| %>
<tr>
    <td>
      <div class="recent-img">
        <%= image_tag line_item.item.display_image_same_item if line_item.item.image.attached? %>
      </div>
    </td>
    <td class=""><%= line_item.item.name %></td>
    <td class=""><%= line_item.item.price %> <%= t("item.dola") %></td>
    <td class="text-center"><%= line_item.quantity %></td>
    <td><%= line_item.total_price %> <%= t("item.dola") %></td>
    <td class="text-right"><%= link_to t("carts.remove"), detail_order_path(line_item), method: :delete, class: "btn btn-sm btn-danger" %> </td>
</tr>
<% end %>

app/views/carts/show.html.erb
<br>
<br>
<br>
<br>
<br>
<br>
<div class="container mb-4" id="cart-box">
    <div class="row">
        <div class="col-12">
            <div class="table-responsive">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th scope="col"></th>
                            <th scope="col"><%= t "carts.product" %></th>
                            <th scope="col"><%= t "carts.price" %></th>
                            <th scope="col" class="text-right"><%= t "carts.quantity" %></th>
                            <th scope="col"><%= t "carts.sub_total" %></th>
                            <th scope="col" class="text-right"><%= t "carts.action" %></th>
                            <th> </th>
                        </tr>
                    </thead>
                    <tbody>
                        <%= render "line_item" %>
                        <tr>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td><strong><%= t "carts.total" %></strong></td>
                            <td class="text-right"><strong><%= @cart.sub_total %> <%= t("item.dola") %></strong></td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
        <div class="col mb-2">
            <div class="row">
                <div class="col-sm-12  col-md-6">
                  <%= link_to t("carts.continue"), root_path, class: "btn btn-block btn-warning" %>
                </div>
                <div class="col-sm-12 col-md-6 text-right">
                    <button class="btn btn-lg btn-block btn-success text-uppercase"><%= t "carts.checkout" %></button>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/categories/_form.html.erb
<%= form_for(@category, url: categories_path) do |form| %>
  <form id="categoryForm">
    <div class="row">
      <div class="col-md-12">
        <div class="form-group">
          <div class="">
            <%= render "shared/error_messages", object: @category %>
          </div>
          <br>
          <br>
          <%= form.label :name, t("category.name_cate") %>
          <%= form.text_field :name,class: "form-control" %>
          <%= form.submit t("category.create_cate") %>
        </div>
      </div>
    </div>
  </form>
<% end %>

app/views/categories/new.html.erb
<br>
<div class="category-box">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <div class="heading-title text-center">
          <h2><%= t "category.add_cate" %></h2>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-12">
        <%= render "form" %>
      </div>
    </div>
  </div>
</div>

app/views/home/_item.html.erb
<% @items.each do |item| %>
  <div class="col-md-4 col-sm-6">
    <div class="our-team">
      <div class="pic">
        <%= image_tag item.display_image if item.image.attached? %>
        <ul class="social">
          <li><a href="#" class="fa fa-linkedin"><%= t "cart" %></a></li>
        </ul>
      </div>
      <div class="team-content">
        <h3 class="title"><%= item.name %></h3>
        <span class="post"><%= t "item.dola" %><%= item.price %></span>
      </div>
    </div>
  </div>
<% end %>

app/views/home/_navigation.html.erb
<div class="nav flex-column nav-pills" id="v-pills-tab" role="tablist" aria-orientation="vertical">
  <%= link_to t("navigate.all"),root_path, class: "nav-link active" %>
  <% @categories.each do |category| %>
    <%= link_to category.name, root_path(:cate => category.id), class: "nav-link" %>
  <% end %>
</div>

app/views/home/_same_item.html.erb
<% @item_same_cate.each do |recent_item| %>
  <div class="recent-box-item">
    <div class="recent-img">
      <%= image_tag recent_item.display_image_same_item if recent_item.image.attached? %>
    </div>
    <div class="recent-info">
      <h4><%= recent_item.name %></h4>
    </div>
  </div>
<% end %>

app/views/home/detail.html.erb
<br>
<!-- Start item details -->
<div class="item-box">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <div class="heading-title text-center">
          <h2><%= t "item.detail_item" %></h2>
          <p><%= t "welcome" %></p>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-xl-8 col-lg-8 col-12">
        <div class="item-inner-details-page">
          <div class="item-inner-box">
            <div class="side-item-img">
              <%= image_tag @item.display_image if @item.image.attached? %>
            </div>
            <div class="inner-item-detail details-page">
              <h3><%=  t "item.name" %><%= @item.name %></h3>
              <h4><%= t "item.price" %><%= @item.price %> $ </h4>
              <h4><%= t "item.description" %></h4>
              <blockquote>
                <h4><%= @item.description %></h4>
              </blockquote>
              <h4><%= t "item.status" %><%= @item.status %></h4>
              <h4><%= t "item.quantity" %><%= @item.quantity %></h4>
              <br>
              <div class="col-sm-12 col-md-6 text-right">
                <button class="btn btn-lg btn-block btn-success text-uppercase">Add to Cart</button>
              </div>
            </div>
          </div>
          <%= render "layouts/comment" %>
          <div class="col-xl-4 col-lg-4 col-md-6 col-sm-8 col-12 item-sidebar">
            <div class="right-side-item">
              <h3>Same Product</h3>
                <div class="post-box-item">
                  <div class="recent-post-box">
                    <%= render "same_item" %>
                  </div>
                </div>
                <h3>Recent Tag</h3>
                <div class="item-tag-box">
                  <ul class="list-inline tag-list">
                    <li class="list-inline-item"><a href="#">Food</a></li>
                    <li class="list-inline-item"><a href="#">Drink</a></li>
                    <li class="list-inline-item"><a href="#">Nature</a></li>
                    <li class="list-inline-item"><a href="#">Italian</a></li>
                    <li class="list-inline-item"><a href="#">Bootstrap4</a></li>
                    <li class="list-inline-item"><a href="#">Fashion</a></li>
                  </ul>
                </div>
              </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
        <!-- End details -->

app/views/home/index.html.erb
<br>
<!-- Start Menu -->
<div class="menu-box">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <div class="heading-title text-center">
          <h2><%= t "menu" %></h2>
          <p><%= t "welcome" %></p>
        </div>
      </div>
    </div>
    <div class="row inner-menu-box">
      <div class="col-3">
        <%= render "navigation" %>
      </div>
      <div class="col-9">
        <div class="tab-content" id="v-pills-tabContent">
          <div class="tab-pane fade show active" id="v-pills-home" role="tabpanel" aria-labelledby="v-pills-home-tab">
            <div class="row">
              <%= render "item" %>
            </div>
          </div>
        </div>
        <%= will_paginate @items %>
      </div>
    </div>
  </div>
</div>
<!-- End Menu -->

app/views/items/_form.html.erb
<%= form_for @item, url: items_path do |form| %>
  <form id="itemForm">
    <div class="">
      <%= render "shared/error_messages", object: @item %>
    </div>
    <div class="row">
      <div class="col-md-12">
        <div class="form-group">
          <%= form.label :name %>
          <%= form.text_field :name,class: "form-control" %>
        </div>
      </div>
      <div class="col-md-12">
        <div class="form-group">
          <%= form.select(:category_id, list_category, class: "custom-select") %>
        </div>
      </div>
      <div class="col-md-12">
        <div class="form-group">
          <%= form.text_area(:description, rows: 5, class: "form-control")%>
        </div>
      </div>
      <div class="col-md-12">
        <div class="form-group">
          <%= form.label :price %>
          <%= form.text_field :price,class: "form-control" %>
        </div>
      </div>
      <div class="col-md-12">
        <div class="form-group">
          <%= form.label :image %>
          <span class="image">
            <%= form.file_field :image, accept: "image/jpeg,image/gif,image/png" %>
          </span>
        </div>
      </div>
      <div class="col-md-12">
        <div class="form-group">
          <%= form.label :quantity %>
          <%= form.text_field :quantity, class: "form-control" %>
        </div>
      </div>
      <div class="col-md-12">
        <div class="submit-button text-center">
          <%= form.submit t("item.create_item") %>
          <div id="msgSubmit" class="h3 text-center hidden"></div>
            <div class="clearfix"></div>
          </div>
       </div>
     </div>
  </form>
<% end %>

app/views/items/new.html.erb
<!-- Start item -->
<br>
<div class="item-box">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <div class="heading-title text-center">
          <h2><%= t "item.new_item" %></h2>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-12">
        <%= render "form" %>
      </div>
    </div>
  </div>
</div>
<!-- End item -->

app/views/users/_form.html.erb
<%= form_for(@user, url: signup_path) do |f| %>
<div id="login-box">
  <div class="left">
    <h1><%= yield(:page_name) %></h1>
    <%= f.label :name %>
    <%= f.text_field :name, type: "text-text" %>
    <%= f.label :email %>
    <%= f.email_field :email, type: "text-text" %>
    <%= f.label :phone %>
    <%= f.text_field :phone, type: "text-text" %>
    <%= f.label :address %>
    <%= f.text_field :address, type: "text-text" %>
    <%= f.label :password %>
    <%= f.password_field :password, type: "password" %>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, type: "password" %>

    <%= f.submit yield(:button_text), class: "btn btn-primary", type: "submit" %>
  </div>
  <div class="right">
    <button class="social-signin facebook"><%= t "login_facebook" %></button>
    <button class="social-signin twitter"><%= t "login_twiter" %></button>
    <button class="social-signin google"><%= t "login_google" %></button>
  </div>
  <div class="or">
    <%= render "shared/error_messages", object: @user %>
  </div>
</div>
<% end %>

app/views/users/new.html.erb
<% provide(:button_text, t("create_my_account")) %>
<% provide(:page_name, t("signup")) %>
<%= render "form" %>