config/routes.rb
Rails.application.routes.draw do
  root "home#index"

  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  get "/signup", to: "users#new"
  post "/signup", to: "users#create"

  resources :users, only: %i{new create}
  resources :categories, only: %i{new create}
  resources :items, only: %i{new create}
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :detail_orders, dependent: :destroy
  has_many :items, through: :detail_orders

  def sub_total
    sum = 0
    detail_orders.each do |line_item|
      sum += line_item.total_price
    end
    sum
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :items, dependent: :destroy

  scope :load_navi, ->{order :name}

  validates :name, presence: true
end

app/models/detail_order.rb
class DetailOrder < ApplicationRecord
  belongs_to :order, optional: true
  belongs_to :item, optional: true
  belongs_to :cart, optional: true

  before_create :set_quantity

  def total_price
    quantity * item.price
  end

  private
  def set_quantity
    self.quantity = 1
  end
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :reviews, dependent: :destroy
  has_many :order_details, dependent: :destroy
  belongs_to :category

  scope :sort_by_name, ->{order :name}
  scope :load_cate, ->(cate){where(category_id: cate)}

  has_one_attached :image
  validates :name, presence: true
  validates :price, presence: true
  validates :quantity, presence: true
  validates :image, content_type: {in: %w(image/jpeg image/gif image/png),
                                   message:
                                    I18n.t("item.image_1")},
   size: {less_than: 5.megabytes, message:
    I18n.t("item.image_2")}

  def display_image
    image.variant resize_to_limit: [Settings.item.image.default,
      Settings.item.image.default]
  end
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :detail_orders, dependent: :destroy
  belongs_to :user, optional: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :item
end

app/models/user.rb
class User < ApplicationRecord
  has_many :reviews, dependent: :destroy
  has_many :orders, dependent: :destroy

  before_save :downcase_email

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i.freeze
  validates :name, presence: true
  validates :email, presence: true,
    length: {maximum: Settings.user.email.size},
    format: {with: VALID_EMAIL_REGEX},
    uniqueness: true
  validates :phone, presence: true
  validates :address, presence: true

  has_secure_password

  def self.digest string
    cost = if ActiveModel::SecurePassword.min_cost
             BCrypt::Engine::MIN_COST
           else
             BCrypt::Engine.cost
           end
    BCrypt::Password.create string, cost: cost
  end

  private

  def downcase_email
    email.downcase!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  include ItemsHelper
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @cart = @current_cart
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:success] = t("category.add_cate_success")
      redirect_to new_category_path
    else
      flash.now[:danger] = t("category.add_cate_fail")
      render :new
    end
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :load_item_by_cate, only: %i(index)

  def index
    @items = Item.paginate(page: params[:page],
      per_page: Settings.item.item_on_page).sort_by_name
    @categories = Category.load_navi
    load_item_by_cate
  end

  private

  def load_item_by_cate
    return if params[:cate].nil?

    @items = Item.paginate(page: params[:page], per_page:
      Settings.item.item_on_page).load_cate(params[:cate]).sort_by_name
    return unless @items.empty?

    flash.now[:danger] = t("item.no_result_with_cate")
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :check_cate, only: %i(new create)

  def new
    @item = Category.item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      flash[:success] = t "item.create_success"
      redirect_to root_path
    else
      flash.now[:danger] = t "item.create_fail"
      render :new
    end
  end

  private

  def item_params
    params.require(:item).permit(:name,
                                 :category_id, :description, :price,
                                 :image, :quantity)
  end

  def check_cate
    return if Category.all.empty?

    flash.now[:success] = t "category.no_cate"
    render :new
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.find_by email: params[:session][:email].downcase
    if user&.authenticate(params[:session][:password])
      login user
      redirect_to root_path
    else
      flash.now[:danger] = t("danger_login")
      redirect_to login_path
    end
  end

  def destroy
    logout
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = t("message_register_success")
      redirect_to root_path
    else
      flash.now[:danger] = t("message_register_error")
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :phone, :address, :password,
                                 :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
  def current_cart
    if session[:cart_id]
      cart = Cart.find_by(id: session[:cart_id])
      if cart.present?
        @current_cart = cart
      else
        session[:cart_id] = nil
      end
    end
    return unless session[:cart_id].nil?

    @current_cart = Cart.create
    session[:cart_id] = @current_cart.id
  end
end

app/helpers/detail_orders_helper.rb
module DetailOrdersHelper
end

app/helpers/items_helper.rb
module ItemsHelper
  def list_category
    Category.pluck(:name)
  end

  def load_item_by_cate
    @categories = Category.all
    cate = params[:cate]
    return if cate.nil?

    @items = Item.load_cate(cate)
    return unless @items.empty?

    flash.now[:danger] = t("item.no_result_with_cate")
  end

  def load_or_search_item
    if params[:search]
      @items = Item.search_item(params[:search])
      return unless @items.empty?

      flash.now[:danger] = t("item.no_result")
    else
      @items = Item.all
    end
  end

  def load_same_item
    samecate = params[:same_cate]
    @item_same_cate = Item.same_cate samecate
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def login user
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by id: session[:user_id]
  end

  def logged_in?
    current_user.present?
  end

  def logout
    session.delete(:user_id)
    @current_user = nil
  end
end

app/views/layouts/_banner.html.erb
<!-- Start All Pages -->
<div class="all-page-title page-breadcrumb">
    <div class="container text-center">
        <div class="row">
            <div class="col-lg-12">
                <h1>Special Menu</h1>
            </div>
        </div>
    </div>
</div>
<!-- End All Pages -->

app/views/layouts/_cart.html.erb
<div class="container mb-4" id="cart-box">
    <div class="row">
        <div class="col-12">
            <div class="table-responsive">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th scope="col"> </th>
                            <th scope="col">Product</th>
                            <th scope="col">Available</th>
                            <th scope="col" class="text-center">Quantity</th>
                            <th scope="col" class="text-right">Price</th>
                            <th> </th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td><img src="https://dummyimage.com/50x50/55595c/fff" /> </td>
                            <td>Product Name Dada</td>
                            <td>In stock</td>
                            <td><input class="form-control" type="text" value="1" /></td>
                            <td class="text-right">124,90 €</td>
                            <td class="text-right"><button class="btn btn-sm btn-danger"><i class="fa fa-trash"></i> </button> </td>
                        </tr>
                        <tr>
                            <td><img src="https://dummyimage.com/50x50/55595c/fff" /> </td>
                            <td>Product Name Toto</td>
                            <td>In stock</td>
                            <td><input class="form-control" type="text" value="1" /></td>
                            <td class="text-right">33,90 €</td>
                            <td class="text-right"><button class="btn btn-sm btn-danger">Detete</button> </td>
                        </tr>
                        <tr>
                            <td><img src="https://dummyimage.com/50x50/55595c/fff" /> </td>
                            <td>Product Name Titi</td>
                            <td>In stock</td>
                            <td><input class="form-control" type="text" value="1" /></td>
                            <td class="text-right">70,00 €</td>
                            <td class="text-right"><button class="btn btn-sm btn-danger">Delete</button> </td>
                        </tr>
                        <tr>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td>Sub-Total</td>
                            <td class="text-right">255,90 €</td>
                        </tr>
                        <tr>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td>Shipping</td>
                            <td class="text-right">6,90 €</td>
                        </tr>
                        <tr>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td><strong>Total</strong></td>
                            <td class="text-right"><strong>346,90 €</strong></td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
        <div class="col mb-2">
            <div class="row">
                <div class="col-sm-12  col-md-6">
                    <button class="btn btn-block btn-warning">Continue Shopping</button>
                </div>
                <div class="col-sm-12 col-md-6 text-right">
                    <button class="btn btn-lg btn-block btn-success text-uppercase">Checkout</button>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/layouts/_comment.html.erb
<div class="blog-comment-box">
    <h3>Comments</h3>
    <div class="comment-item">
        <div class="comment-item-left">
            <img src="/assets/avt-img.jpg" alt="">
        </div>
        <div class="comment-item-right">
            <div class="pull-left">
                <a href="#">Rubel Ahmed</a>
            </div>
            <div class="pull-right">
                <i class="fa fa-clock-o" aria-hidden="true"></i>Time : <span>11.30 am</span>
            </div>
            <div class="des-l">
                <p>Morbi lacinia ultrices lorem id tincidunt. Cras id dui risus. Pellentesque consectetur id mi sed pharetra. Proin imperdiet gravida nisl, sit amet varius urna. In auctor.</p>
            </div>
            <a href="#" class="right-btn-re"><i class="fa fa-reply" aria-hidden="true"></i> Reply</a>
        </div>
    </div>
    <div class="comment-item children">
        <div class="comment-item-left">
            <img src="/assets/avt-img.jpg" alt="">
        </div>
        <div class="comment-item-right">
            <div class="pull-left">
                <a href="#">Admin</a>
            </div>
            <div class="pull-right">
                <i class="fa fa-clock-o" aria-hidden="true"></i>Time : <span>1.30 pm</span>
            </div>
            <div class="des-l">
                <p>Morbi lacinia ultrices lorem id tincidunt. Cras id dui risus. Pellentesque consectetur id mi sed pharetra. Proin imperdiet gravida nisl, sit amet varius urna. In auctor.</p>
            </div>
            <a href="#" class="right-btn-re"><i class="fa fa-reply" aria-hidden="true"></i> Reply</a>
        </div>
    </div>
    <div class="comment-item">
        <div class="comment-item-left">
            <img src="/assets/avt-img.jpg" alt="">
        </div>
        <div class="comment-item-right">
            <div class="pull-left">
                <a href="#">Rubel Ahmed</a>
            </div>
            <div class="pull-right">
                <i class="fa fa-clock-o" aria-hidden="true"></i>Time : <span>11.30 am</span>
            </div>
            <div class="des-l">
                <p>Morbi lacinia ultrices lorem id tincidunt. Cras id dui risus. Pellentesque consectetur id mi sed pharetra. Proin imperdiet gravida nisl, sit amet varius urna. In auctor.</p>
            </div>
            <a href="#" class="right-btn-re"><i class="fa fa-reply" aria-hidden="true"></i> Reply</a>
        </div>
    </div>
</div>
<div class="comment-respond-box">
    <h3>Leave your comment </h3>
    <div class="comment-respond-form">
        <form id="commentrespondform" class="comment-form-respond row" method="post">
            <div class="col-lg-6 col-md-6 col-sm-6">
                <div class="form-group">
                    <input id="name_com" class="form-control" name="name" placeholder="Name" type="text">
                </div>
                <div class="form-group">
                    <input id="email_com" class="form-control" name="email" placeholder="Your Email" type="email">
                </div>
            </div>
            <div class="col-lg-6 col-md-6 col-sm-6">
                <div class="form-group">
                    <textarea class="form-control" id="textarea_com" placeholder="Your Message" rows="2"></textarea>
                </div>
            </div>
            <div class="col-lg-12 col-md-12 col-sm-12">
                <button class="btn btn-submit">Submit comment</button>
            </div>
        </form>
    </div>
</div>
</div>
</div>

app/views/layouts/_detailItem.html.erb
<!-- Start All Pages -->
<div class="all-page-title page-breadcrumb">
    <div class="container text-center">
        <div class="row">
            <div class="col-lg-12">
                <h1>Items</h1>
            </div>
        </div>
    </div>
</div>
<!-- End All Pages -->

<!-- Start item details -->
<div class="item-box">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="heading-title text-center">
                    <h2>Items</h2>
                    <p>Lorem Ipsum is simply dummy text of the printing and typesetting</p>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-xl-8 col-lg-8 col-12">
                <div class="item-inner-details-page">
                    <div class="item-inner-box">
                        <div class="side-item-img">
                            <img class="img-fluid" src="/assets/inner-item-img.jpg" alt="">
                            <div class="date-item-up">
                                27 Fab
                            </div>
                        </div>
                        <div class="inner-item-detail details-page">
                            <h3>Duis feugiat neque sed dolor cursus, sed lacinia nisl pretium.</h3>
                            <ul>
                                <li><i class="zmdi zmdi-account"></i>Posted By : <span>Rubel Ahmed</span></li>
                                <li>|</li>
                                <li><i class="zmdi zmdi-time"></i>Time : <span>11.30 am</span></li>
                            </ul>
                            <p>Price</p>
                            <p>Discount</p>
                            <blockquote>
                                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non feugiat lacus. Nunc nisi velit, consectetur vitae ex porttitor, placerat scelerisque mauris. Phasellus sit amet tincidunt metus, quis tempus ex. Quisque in lorem ut mi ullamcorper suscipit eu nec purus. Nam maximus sagittis iaculis.</p>
                            </blockquote>
                            <p>Category</p>
                            <p>Status</p>
                            <p>Quantity</p>
                        </div>
                    </div>

                    <%= render "layouts/comment" %>

                    <div class="col-xl-4 col-lg-4 col-md-6 col-sm-8 col-12 item-sidebar">
                        <div class="right-side-item">
                            <h3>Search</h3>
                            <div class="item-search-form">
                                <input name="search" placeholder="Search item" type="text">
                                <button class="search-btn">
                                    <i class="fa fa-search" aria-hidden="true"></i>
                                </button>
                            </div>
                            <h3>Categories</h3>
                            <div class="item-categories">
                                <ul>
                                    <li><a href="#"><span>Food</span></a></li>
                                    <li><a href="#"><span>Pizza</span></a></li>
                                    <li><a href="#"><span>Drink</span></a></li>
                                    <li><a href="#"><span>Lorem Sit</span></a></li>
                                    <li><a href="#"><span>Burger</span></a></li>
                                    <li><a href="#"><span>Music</span></a></li>
                                </ul>
                            </div>
                            <h3>Recent Post</h3>
                            <div class="post-box-item">
                                <div class="recent-post-box">
                                    <div class="recent-box-item">
                                        <div class="recent-img">
                                            <img class="img-fluid" src="/assets/post-img-01.jpg" alt="">
                                        </div>
                                        <div class="recent-info">
                                            <ul>
                                                <li><i class="zmdi zmdi-account"></i>Posted By : <span>Rubel Ahmed</span></li>
                                                <li>|</li>
                                                <li><i class="zmdi zmdi-time"></i>Time : <span>11.30 am</span></li>
                                            </ul>
                                            <h4>Duis feugiat neque sed dolor cursus, sed lacinia nisl pretium.</h4>
                                        </div>
                                    </div>
                                    <div class="recent-box-item">
                                        <div class="recent-img">
                                            <img class="img-fluid" src="/assets/post-img-02.jpg" alt="">
                                        </div>
                                        <div class="recent-info">
                                            <ul>
                                                <li><i class="zmdi zmdi-account"></i>Posted By : <span>Rubel Ahmed</span></li>
                                                <li>|</li>
                                                <li><i class="zmdi zmdi-time"></i>Time : <span>11.30 am</span></li>
                                            </ul>
                                            <h4>Duis feugiat neque sed dolor cursus, sed lacinia nisl pretium.</h4>
                                        </div>
                                    </div>
                                    <div class="recent-box-item">
                                        <div class="recent-img">
                                            <img class="img-fluid" src="/assets/post-img-03.jpg" alt="">
                                        </div>
                                        <div class="recent-info">
                                            <ul>
                                                <li><i class="zmdi zmdi-account"></i>Posted By : <span>Rubel Ahmed</span></li>
                                                <li>|</li>
                                                <li><i class="zmdi zmdi-time"></i>Time : <span>11.30 am</span></li>
                                            </ul>
                                            <h4>Duis feugiat neque sed dolor cursus, sed lacinia nisl pretium.</h4>
                                        </div>
                                    </div>
                                    <div class="recent-box-item">
                                        <div class="recent-img">
                                            <img class="img-fluid" src="/assets/post-img-01.jpg" alt="">
                                        </div>
                                        <div class="recent-info">
                                            <ul>
                                                <li><i class="zmdi zmdi-account"></i>Posted By : <span>Rubel Ahmed</span></li>
                                                <li>|</li>
                                                <li><i class="zmdi zmdi-time"></i>Time : <span>11.30 am</span></li>
                                            </ul>
                                            <h4>Duis feugiat neque sed dolor cursus, sed lacinia nisl pretium.</h4>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <h3>Recent Tag</h3>
                            <div class="item-tag-box">
                                <ul class="list-inline tag-list">
                                    <li class="list-inline-item"><a href="#">Food</a></li>
                                    <li class="list-inline-item"><a href="#">Drink</a></li>
                                    <li class="list-inline-item"><a href="#">Nature</a></li>
                                    <li class="list-inline-item"><a href="#">Italian</a></li>
                                    <li class="list-inline-item"><a href="#">Bootstrap4</a></li>
                                    <li class="list-inline-item"><a href="#">Fashion</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
        <!-- End details -->

app/views/layouts/_footer.html.erb
<!-- Start Footer -->
<footer class="footer-area bg-f">
    <div class="container">
        <div class="row">
            <div class="col-lg-3 col-md-6">
                <h3>About Us</h3>
                <p>Integer cursus scelerisque ipsum id efficitur. Donec a dui fringilla, gravida lorem ac, semper magna. Aenean rhoncus ac lectus a interdum. Vivamus semper posuere dui.</p>
            </div>
            <div class="col-lg-3 col-md-6">
                <h3>Subscribe</h3>
                <div class="subscribe_form">
                    <form class="subscribe_form">
                        <input name="EMAIL" id="subs-email" class="form_input" placeholder="Email Address..." type="email">
                        <button type="submit" class="submit">SUBSCRIBE</button>
                        <div class="clearfix"></div>
                    </form>
                </div>
                <ul class="list-inline f-social">
                    <li class="list-inline-item"><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
                    <li class="list-inline-item"><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
                    <li class="list-inline-item"><a href="#"><i class="fa fa-linkedin" aria-hidden="true"></i></a></li>
                    <li class="list-inline-item"><a href="#"><i class="fa fa-google-plus" aria-hidden="true"></i></a></li>
                    <li class="list-inline-item"><a href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
                </ul>
            </div>
            <div class="col-lg-3 col-md-6">
                <h3>Contact information</h3>
                <p class="lead">Ipsum Street, Lorem Tower, MO, Columbia, 508000</p>
                <p class="lead"><a href="#">+01 2000 800 9999</a></p>
                <p><a href="#"> info@admin.com</a></p>
            </div>
            <div class="col-lg-3 col-md-6">
                <h3>Opening hours</h3>
                <p><span class="text-color">Monday: </span>Closed</p>
                <p><span class="text-color">Tue-Wed :</span> 9:Am - 10PM</p>
                <p><span class="text-color">Thu-Fri :</span> 9:Am - 10PM</p>
                <p><span class="text-color">Sat-Sun :</span> 5:PM - 10PM</p>
            </div>
        </div>
    </div>

    <div class="copyright">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <p class="company-name">All Rights Reserved. &copy; 2018 <a href="#">Live Dinner Restaurant</a> Design By :
                        <a href="https://html.design/">html design</a></p>
                </div>
            </div>
        </div>
    </div>

</footer>
<!-- End Footer -->

app/views/layouts/_header.html.erb
<!-- Start header -->
<header class="top-navbar">
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
      <a class="navbar-brand" href="index.html">
        <img src="/assets/logo.png" alt="" />
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbars-rs-food" aria-controls="navbars-rs-food" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbars-rs-food">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item active"><%= link_to t("menu"),root_path, class: "nav-link" %></li>
          <li class="nav-item"><%= link_to t("signup"), signup_path, class: "nav-link"%></li>
          <% if logged_in? %>
            <li class="nav-item"><%= link_to t("logout"), logout_path, method: "delete", class: "nav-link"%></li>
          <% else %>
            <li class="nav-item"><%= link_to t("login"), login_path, class: "nav-link"%></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>
<br>

app/views/layouts/_signup.html.erb
<div id="login-box">
    <div class="left">
        <h1>Sign up</h1>

        <input type="text" name="username" placeholder="Username" />
        <input type="text" name="email" placeholder="E-mail" />
        <input type="password" name="password" placeholder="Password" />
        <input type="password" name="password2" placeholder="Retype password" />

        <input type="submit" name="signup_submit" value="Sign me up" />
    </div>

    <div class="right">
        <span class="loginwith">Sign in with<br />social network</span>

        <button class="social-signin facebook">Log in with facebook</button>
        <button class="social-signin twitter">Log in with Twitter</button>
        <button class="social-signin google">Log in with Google+</button>
    </div>
    <div class="or">OR</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Oe42DnFoodAndDrink</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_pack_tag "application", "data-turbolinks-track": "reload" %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <div class="">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
    </div>
    <%= yield %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
<div id="error_explanation">
  <div class="alert alert-danger">
    <%= t("count_err", count: object.errors.count) %>
  </div>
  <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>